export const Veggies = [
    {
        id: 1,
        title: "Green chilli",
        image: "https://c4.wallpaperflare.com/wallpaper/147/545/208/nature-basket-apples-grapes-wallpaper-preview.jpg",
        price: 29,
        originalprice: 35,
        ratting: 3.6,
        delivertime: 8,
        weight: 200,
        category: "veggies",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 2,
        title: "Tamato",
        image: "https://c1.wallpaperflare.com/preview/332/477/68/meat-lamb-t-bone-steak-hille-gourmets.jpg",
        price: 22,
        originalprice: 30,
        ratting: 3.6,
        delivertime: 6,
        weight: 400,
        category: "nonveg",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 3,
        title: "Mushroom puttago",
        image: "https://preview.redd.it/are-you-an-ice-cream-cup-cone-or-stick-person-v0-dbrb76ybey6d1.jpeg?auto=webp&s=f2a1655f0ab817de92292d730a7885ff986c2a10",
        price: 85,
        originalprice: 106,
        ratting: 3.6,
        delivertime: 10,
        weight: 200,
        category: "Bread & Eggs",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 4,
        title: "Banana",
        image: "https://5.imimg.com/data5/SELLER/Default/2023/11/357616545/BT/EA/IL/38463093/images-500x500.jpg",
        price: 31,
        originalprice: 82,
        ratting: 3.6,
        delivertime: 10,
        weight: "1000",
        category: "masala",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 5,
        title: "pineapple slice",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBnjw2Paz-kZrlSwKg6SQFeZx5A33Xskjqf9qtwndudietrJX_JPFnK9qZC9ipyNLHFDE&usqp=CAU",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "breakfast",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 6,
        title: "pineapple slice",
        image: "https://media.istockphoto.com/id/1412889493/photo/survival-set-of-nonperishable-foods-in-carton-box.jpg?s=612x612&w=0&k=20&c=e_FwIoAoYieBzBPJmVrYdvt2Wye9iM_AIjaphWCYWRI=",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "Att Rice & Oils",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 7,
        title: "Green chilli",
        image: "https://c4.wallpaperflare.com/wallpaper/147/545/208/nature-basket-apples-grapes-wallpaper-preview.jpg",
        price: 29,
        originalprice: 35,
        ratting: 3.6,
        delivertime: 8,
        weight: 200,
        category: "veggies",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 8,
        title: "Green chilli",
        image: "https://c4.wallpaperflare.com/wallpaper/147/545/208/nature-basket-apples-grapes-wallpaper-preview.jpg",
        price: 29,
        originalprice: 35,
        ratting: 3.6,
        delivertime: 8,
        weight: 200,
        category: "veggies",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 9,
        title: "Green chilli",
        image: "https://c4.wallpaperflare.com/wallpaper/147/545/208/nature-basket-apples-grapes-wallpaper-preview.jpg",
        price: 29,
        originalprice: 35,
        ratting: 3.6,
        delivertime: 8,
        weight: 200,
        category: "veggies",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 10,
        title: "Green chilli",
        image: "https://c4.wallpaperflare.com/wallpaper/147/545/208/nature-basket-apples-grapes-wallpaper-preview.jpg",
        price: 29,
        originalprice: 35,
        ratting: 3.6,
        delivertime: 8,
        weight: 200,
        category: "veggies",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 11,
        title: "Tea,Coffe",
        image: "https://c4.wallpaperflare.com/wallpaper/147/545/208/nature-basket-apples-grapes-wallpaper-preview.jpg",
        price: 29,
        originalprice: 35,
        ratting: 3.6,
        delivertime: 8,
        weight: 200,
        category: "snacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 12,
        title: "Icecream & More",
        image: "https://c1.wallpaperflare.com/preview/332/477/68/meat-lamb-t-bone-steak-hille-gourmets.jpg",
        price: 22,
        originalprice: 30,
        ratting: 3.6,
        delivertime: 6,
        weight: 400,
        category: "snacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 13,
        title: "Frozen Food",
        image: "https://preview.redd.it/are-you-an-ice-cream-cup-cone-or-stick-person-v0-dbrb76ybey6d1.jpeg?auto=webp&s=f2a1655f0ab817de92292d730a7885ff986c2a10",
        price: 85,
        originalprice: 106,
        ratting: 3.6,
        delivertime: 10,
        weight: 200,
        category: "snacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 14,
        title: "Sweet Cravings",
        image: "https://5.imimg.com/data5/SELLER/Default/2023/11/357616545/BT/EA/IL/38463093/images-500x500.jpg",
        price: 31,
        originalprice: 82,
        ratting: 3.6,
        delivertime: 10,
        weight: "1000",
        category: "snacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 15,
        title: "Colud Drinks & Juices",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBnjw2Paz-kZrlSwKg6SQFeZx5A33Xskjqf9qtwndudietrJX_JPFnK9qZC9ipyNLHFDE&usqp=CAU",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "snacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 16,
        title: "Munchies",
        image: "https://media.istockphoto.com/id/1412889493/photo/survival-set-of-nonperishable-foods-in-carton-box.jpg?s=612x612&w=0&k=20&c=e_FwIoAoYieBzBPJmVrYdvt2Wye9iM_AIjaphWCYWRI=",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "snacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 17,
        title: "Bipto Cafe",
        image: "https://media.istockphoto.com/id/1412889493/photo/survival-set-of-nonperishable-foods-in-carton-box.jpg?s=612x612&w=0&k=20&c=e_FwIoAoYieBzBPJmVrYdvt2Wye9iM_AIjaphWCYWRI=",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "snacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 18,
        title: "Biscuits & Cookies",
        image: "https://media.istockphoto.com/id/1412889493/photo/survival-set-of-nonperishable-foods-in-carton-box.jpg?s=612x612&w=0&k=20&c=e_FwIoAoYieBzBPJmVrYdvt2Wye9iM_AIjaphWCYWRI=",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "snacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 18,
        title: "Packaged Food",
        image: "https://media.istockphoto.com/id/1412889493/photo/survival-set-of-nonperishable-foods-in-carton-box.jpg?s=612x612&w=0&k=20&c=e_FwIoAoYieBzBPJmVrYdvt2Wye9iM_AIjaphWCYWRI=",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "snacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 19,
        title: "biryani",
        image: "https://media.istockphoto.com/id/1412889493/photo/survival-set-of-nonperishable-foods-in-carton-box.jpg?s=612x612&w=0&k=20&c=e_FwIoAoYieBzBPJmVrYdvt2Wye9iM_AIjaphWCYWRI=",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "biryani",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 20,
        title: "Dhum biryani",
        image: "https://media.istockphoto.com/id/1412889493/photo/survival-set-of-nonperishable-foods-in-carton-box.jpg?s=612x612&w=0&k=20&c=e_FwIoAoYieBzBPJmVrYdvt2Wye9iM_AIjaphWCYWRI=",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "biryani",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 21,
        title: "Pulav biryani",
        image: "https://media.istockphoto.com/id/1412889493/photo/survival-set-of-nonperishable-foods-in-carton-box.jpg?s=612x612&w=0&k=20&c=e_FwIoAoYieBzBPJmVrYdvt2Wye9iM_AIjaphWCYWRI=",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "biryani",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 22,
        title: "Pulav biryani",
        image: "https://media.istockphoto.com/id/1412889493/photo/survival-set-of-nonperishable-foods-in-carton-box.jpg?s=612x612&w=0&k=20&c=e_FwIoAoYieBzBPJmVrYdvt2Wye9iM_AIjaphWCYWRI=",
        price: 98,
        originalprice: 119,
        ratting: 3.6,
        delivertime: 13,
        weight: "180",
        category: "masala",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    },
    {
        id: 23,
        title: "Green chilli",
        image: "https://media.istockphoto.com/id/1204481619/photo/raw-green-organic-serrano-peppers.jpg?s=612x612&w=0&k=20&c=k-j3yR77qNlBnWX0cySpBQSE-GY0kQjYRLnbgDnMfPg=",
        price: 29,
        originalprice: 35,
        ratting: 3.6,
        delivertime: 8,
        weight: 200,
        category: "veggies",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula."
    }
]

export const Categorisall = [
    {
        id: 1,
        category: "lunch",
        image: "https://img.freepik.com/free-photo/top-view-table-full-delicious-food-composition_23-2149141352.jpg?semt=ais_hybrid&w=740",
    },
    {
        id: 2,
        category: "snacks",
        image: "https://static.vecteezy.com/system/resources/previews/013/934/267/non_2x/indian-tea-time-snacks-in-group-sev-chivda-farsan-mixture-bakarwadi-served-in-different-bowls-free-photo.jpg",
    },
    {
        id: 3,
        category: "veggies",
        image: "https://c4.wallpaperflare.com/wallpaper/147/545/208/nature-basket-apples-grapes-wallpaper-preview.jpg",
    },
    {
        id: 4,
        category: "salads",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKD2OLIXOiCopVEQoMJIvSGt2NJVIVmQ288Q&s",
    }, {
        id: 5,
        category: "nonveg",
        image: "https://c1.wallpaperflare.com/preview/332/477/68/meat-lamb-t-bone-steak-hille-gourmets.jpg",
    },
    {
        id: 6,
        category: "Bread & Eggs",
        image: "https://media.istockphoto.com/id/177360383/photo/cheese-bread-milk-and-eggs.jpg?s=612x612&w=0&k=20&c=8LN01R9z5tnalaOCj9rHhN_ut7bN3KBOBS-cVEDGVi8=",
    },
    {
        id: 7,
        category: "masala",
        image: "https://5.imimg.com/data5/SELLER/Default/2023/11/357616545/BT/EA/IL/38463093/images-500x500.jpg",
    },
    {
        id: 8,
        category: "breakfast",
        image: "https://img.freepik.com/free-photo/toast-half-fried-egg-salad-bacon-gray-plate-near-tea-cup_23-2148067057.jpg?semt=ais_hybrid&w=740",

    },
    {
        id: 9,
        category: "Dinners",
        image: "https://thumbs.dreamstime.com/b/assortment-indian-dishes-dinner-butter-chicken-tikka-masala-rice-naan-basmati-162829221.jpg",
    }
]